# Generated by Django 4.2 on 2023-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_reg_no', models.IntegerField()),
                ('student_branch', models.CharField(max_length=20)),
                ('student_batch', models.CharField(max_length=10)),
            ],
        ),
    ]
