# Generated by Django 4.2 on 2023-04-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollegeDatabase',
            new_name='Student',
        ),
    ]
